@startuml

'autonumber
actor       Owner                       as o
actor       Collector                   as c
entity      "Contract\n<<deployed>>"    as contract

== Contract interaction ==
c -> contract : calls mint()
activate contract
contract -> contract : writes transaction\n(address, tokenID)
activate contract
deactivate contract
contract --> c : emits event
deactivate contract

c -> contract : calls tokenURI(tokenID)
activate contract
contract --> c : returns ciphered data
deactivate contract

== Reveal ==
o -> contract : calls reveal(key,initialVector)
activate contract
contract -> contract : updates private\nfields _key & _initialVector
activate contract
deactivate contract
contract -> contract : deciphers inplace
'deactivate contract
activate contract
deactivate contract
contract --> o : emits event
deactivate contract
c -> contract : calls tokenURI(tokenID)
activate contract
contract --> c : returns deciphered data
deactivate contract

@enduml
