@startuml
skinparam linetype ortho
left to right direction

actor Owner as O

rectangle "Contract creation"{
    O -> (4. Send hidden\nsecret to\ncontract)
    (2. Create\nContract) <-[norank]- O
    O -[norank]-> (1. Cipher\nSecret)
    O -> (3. Deploy\nContract)
}

'---------------------------------------------
newpage

skinparam linetype ortho
left to right direction

actor "Collector" as C

rectangle "Collector's interaction with the contract" as interaction{
    C -> (2. Get TokenURI)
    C -> (1. Mint Token)
}

C -[hidden]left-> interaction

note right of (2. Get TokenURI)
    The collector can get the 
    secret only if that token 
    has been minted.
    The token's metadata are 
    keept secret until the owner 
    reveal it.
end note

'---------------------------------------------
newpage

skinparam linetype ortho
left to right direction
actor Owner as O
actor "Collector" as C

rectangle "Reveal"{
    (2. Get\nRevealed Secret) <-up- C
    O -down-> (1. Reveal Secret)
}

@enduml